Repository DevLab-umontp/Librairie-Java-EDT, pull requests merged in 2021-01, with the labels that each got.

#22 💚 Ajout CI SonarCloud
  .github/workflows/sonarclourd.yml
  pom.xml
Labels: CI/CD

#23 🚀 Publication du package
  pom.xml
  src/main/java/fr/umontp/edt/Cours.java
  src/main/java/fr/umontp/edt/EmploiDuTemps.java
  src/main/java/fr/umontp/edt/EmploiDuTempsProxy.java
  src/main/java/fr/umontp/edt/Groupe.java
  src/main/java/fr/umontp/edt/InterfaceEmploiDuTemps.java
  src/main/java/fr/umontp/edt/Planifiable.java
  src/main/java/fr/umontp/edt/Planning.java
  src/test/java/fr/umontp/edt/CoursTest.java
  src/test/java/fr/umontp/edt/EmploiDuTempsProxyTest.java
  src/test/java/fr/umontp/edt/EmploiDuTempsTest.java
  src/test/java/fr/umontp/edt/GroupeTest.java
  src/test/java/fr/umontp/edt/PlanningTest.java
Labels: Déploiement

#24 💚 sonar inclusions
  pom.xml
  src/main/java/fr/umontp/edt/Groupe.java
Labels: CI/CD

#25 📝 Mise à jour de la Documentation
  LICENSE
  README.md
  ressources/pom.xml
Labels: documentation

#28 🚀 CI maven package
  .github/CODEOWNERS
  .github/workflows/maven-package.yml
  pom.xml
Labels: CI/CD, Déploiement

#30 ✨ Ajout de nouvelles Features
  .github/workflows/maven-package.yml
  .github/workflows/maven.yml
  .gitignore
  README.md
  ressources/ExempleDeCode.java
  src/main/java/fr/umontp/edt/Cours.java
  src/main/java/fr/umontp/edt/EmploiDuTemps.java
  src/main/java/fr/umontp/edt/EmploiDuTempsProxy.java
  src/main/java/fr/umontp/edt/Groupe.java
  src/main/java/fr/umontp/edt/InterfaceEmploiDuTemps.java
  src/main/java/fr/umontp/edt/Planifiable.java
  src/main/java/fr/umontp/edt/Planning.java
  src/main/java/fr/umontp/edt/PlanningFiltreur.java
  src/main/java/fr/umontp/edt/Professeur.java
  src/main/java/fr/umontp/edt/RepertoireProfesseur.java
  src/test/java/fr/umontp/edt/CoursTest.java
  src/test/java/fr/umontp/edt/EmploiDuTempsProxyTest.java
  src/test/java/fr/umontp/edt/EmploiDuTempsTest.java
  src/test/java/fr/umontp/edt/PlanningFiltreurTest.java
  src/test/java/fr/umontp/edt/PlanningTest.java
  src/test/java/fr/umontp/edt/ProfesseurTest.java
  src/test/java/fr/umontp/edt/RepertoireProfesseurTest.java
Labels: enhancement
